# Generated by Django 3.2.7 on 2021-09-28 18:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0002_auto_20210922_1624'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rubrics',
            options={'ordering': ['id'], 'verbose_name': 'Rubric', 'verbose_name_plural': 'Rubrics'},
        ),
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
